//
// Created by Rogue on 5/27/2022.
//

#ifndef STUDENTRECORDSYSTEM_SINGLYLINKEDLIST_H
#define STUDENTRECORDSYSTEM_SINGLYLINKEDLIST_H

class SinglyLinkedList{

};

#endif //STUDENTRECORDSYSTEM_SINGLYLINKEDLIST_H
